### ISSUE TITLE
CartTags createForm sometimes throws str_replace() error in Antlers runtime

### ISSUE THREAD

**Issue by Web10-Joris** [doublethreedigital/simple-commerce#1047]
### Description

Hi Duncan, in the update cart form sometimes this error occurs. I don't know what this means, and havent experienced any weird behaviour on these forms. But wanted to share it with you, just in case you recognizes the issue maybe.  

https://flareapp.io/share/V7jkaMO5

### Steps to reproduce

Not 100% sure how to reproduce, only occurs sometimes on the checkout page of my website (where the cart update form tag is used). 

### Environment

Environment
Application Name: xxxxx
Laravel Version: 10.47.0
PHP Version: 8.2.15
Composer Version: 2.7.2
Environment: production
Debug Mode: OFF
URL: xxxxx.nl
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily, flare
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR, EUR, EUR, EUR
Gateways: Mollie
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: MTC Pallet Zending, PostNL International
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 7
Antlers: runtime
Sites: 4 (Nederlands, Duits, Engels, Pools)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.52.0 PRO

Statamic Addons
aerni/advanced-seo: 2.4.4
duncanmcclean/simple-commerce: 6.0.10
heidkaemper/statamic-toolbar: 1.1.2
statamic-rad-pack/runway: 6.4.1
statamic/collaboration: 0.8.1
web10/back-in-stock-notifier: dev-main
web10/language-switcher: dev-main

**Comment by duncanmcclean** [comment]
Usually, this error occurs when there's a syntax error in the Antlers template, rather than it being a Simple Commerce issue.

**Comment by Web10-Joris** [comment]
Hmm okay! Thanks for the info. Weird that it then only happens sometimes and not on all requests... Wil check it myself :)
