### ISSUE TITLE
Mollie Bank Transfer: Status Open redirects to error_redirect page 

### ISSUE THREAD

**Issue by Web10-Joris** [doublethreedigital/simple-commerce#1150]
### Description

When customers use [Mollie Bank Transfer](https://www.mollie.com/payments/bank-transfer) for checkout, an issue arises. Currently, SC redirects customers to the `error_redirect` page because the order isn't immediately marked as "Paid". This occurs despite customers receiving an email or QR code from Mollie with bank transfer details.

The problem is that these orders remain "Open" in Mollie's system for several days, allowing customers to complete the transfer later. However, customers see the `error_redirect` page (as defined in the offsite tag) and may assume their order failed completely. This discourages them from completing the bank transfer, even though successful payments within X days would still be marked as "Paid" in SC.

Some ideas to fix this in the next version: 
- Adding a new payment status called "Open"
- Updating the redirect behavior for this status

This way, when Mollie receives the payment in their bank account, they can update the status to "Paid" via webhook.
As a temporary measure, we've disabled this payment method in Mollie to avoid confusion.

### Steps to reproduce

 N/A

### Environment

N/A

**Comment by duncanmcclean** [comment]
I don't have time to look into this now, but the fix is _might_ as simple as allowing for the `Open` status here: https://github.com/duncanmcclean/simple-commerce/blob/7.x/src/Gateways/Builtin/MollieGateway.php#L78

Although, we probably have to be careful that we only take them back to `redirect` if it's a manual bank transfer payment.

**Comment by Web10-Joris** [comment]
Good one. I'm not sure if there are indeed other methods that also return `Open` on success. 
My initial idea was to extend and keep track of it as a different `PaymentStatus::Open`, as you might want to wait with fulfilling the order until it is actually `Paid`.

**Comment by duncanmcclean** [comment]
I've just taken a quick look into this... 

I don't think we can consider "Open" to be a successful status. As soon as a payment is created, it shows as "Open" in the Mollie dashboard.

![CleanShot 2024-11-22 at 22 48 55](https://github.com/user-attachments/assets/e45b875e-1106-4da3-a46d-36c7ed2d932c)

There doesn't seem to be anything on the Mollie `Payment` object to indicate whether a bank transfer has been started but not completed yet.

![CleanShot 2024-11-22 at 22 45 14](https://github.com/user-attachments/assets/d7b56872-0420-4f00-af30-894dea43989e)

I don't have any other ideas, unfortunatley.

**Comment by Web10-Joris** [comment]
> I don't have any other ideas, unfortunatley


No problem, me neither, so let's close it for now. Thanks for looking into it 😀
