### ISSUE TITLE
[Feature Request] Make cart work with full static caching

### ISSUE THREAD

**Issue by twd3** [doublethreedigital/simple-commerce#321]
It would be so cool if Simple Commerce worked with full static caching turned on. Maybe you could work your magic using Ajax/Alpine and the dynamic CSFR token from the Peak starter kit? https://github.com/studio1902/statamic-peak#forms

**Comment by damcclean** [comment]
As per our conversation on Discord, here's the current situation as of v2.1:

From the side of things where Simple Commerce uses Forms, for example, the add to cart form or the checkout form, they should work fine as long as 

1) the user has a cart assigned to them (currently can only be done with sessions, but cookie support for that is coming in v2.2). 
2) as long as you've got a CSRF token somehow. From looking briefly into Peak, it looks like it grabs the CSRF token over AJAX so you should be good to go there!

Simple Commerce also has some non-form things, like displaying the number of items in the users' cart, getting items from cart, displaying previous orders. As these are provided by the Simple Commerce tag on each request, it's not possible to use these while using static caching.

A way around this, however, would be to make a network request with JavaScript to fetch information about the customer's cart etc, that way you can dynamically add it to the DOM after the static page has been loaded. It's probably you could store in a local store like Vuex or [Spruce](https://github.com/ryangjchandler/spruce), if you're using Alpine.js. 

The controllers for that workaround aren't currently built-in to Simple Commerce (as I've not thought of static caching until now) but I'll add it to my roadmap for features to build in the next couple of versions.

Thanks for pointing this out! Have a Merry Christmas! 🎄
