### ISSUE TITLE
"Money" field type in Product Variants failing to load

### ISSUE THREAD

**Issue by mscruse** [doublethreedigital/simple-commerce#454]
### Description

I added a second field of type "Money" to the "Product Variants" field so that I can create specials.

This works great and I can output the value at the front end and see it in the product .md file, but when I go back to edit the product the new "Compare Price" field is blank.

To test this I also added a simple text field and that works perfectly.

<img width="1415" alt="Screen Shot 2021-08-26 at 5 34 37 pm" src="https://user-images.githubusercontent.com/22737928/130921829-253814c9-2be7-48f9-a46c-9efb90efc4d6.png">

<img width="896" alt="Screen Shot 2021-08-26 at 5 34 28 pm" src="https://user-images.githubusercontent.com/22737928/130921857-90c0bb35-7ce3-45e7-a42e-9bc64f1aa044.png">

<img width="1455" alt="Screen Shot 2021-08-26 at 5 35 01 pm" src="https://user-images.githubusercontent.com/22737928/130921882-339b4fed-442a-47a5-a999-af95b9225ce2.png">

<img width="440" alt="Screen Shot 2021-08-26 at 5 40 04 pm" src="https://user-images.githubusercontent.com/22737928/130921915-cc587e4d-c539-4ad0-a826-ee1a9051674f.png">

### Steps to reproduce

1. Add new field to Product Variants of type "Money" called "Compare Price"
2. Edit product to add value in new "Compare Price" field.
3. Save then edit the product again - Compare Price field is blank.

### Environment

Statamic 3.2.0 Solo
Laravel 8.56.0
PHP 8.0.1
doublethreedigital/sc-digital-products 2.2.1
doublethreedigital/simple-commerce 2.3.19

**Comment by duncanmcclean** [comment]
Thanks, I'll take a look at this after work!

**Comment by duncanmcclean** [comment]
Fixed in [v2.3.20](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.20)
