### ISSUE TITLE
Orders export

### ISSUE THREAD

**Issue by remiduval** [doublethreedigital/simple-commerce#482]
### What would you like to see added?

It would be great to be able to export Orders for accounting purposes.

There are some export plugins in the Marketplace already but the _items_ field is too specific to SC:
- you can't filter/export by product
- all data from the _items_ field is exported as json inside a single column
- extra fields are not present in the output (one column for each would be great)

### Is there a workaround you can use in the meantime?

Partial workaround: Export plugins from the Marketplace

### Priority wise - where's this feature for you?

Will need it in the next few weeks

**Comment by duncanmcclean** [comment]
What format do you need to be able to export in?

**Comment by remiduval** [comment]
CSV, ODS or XLS would work

**Comment by duncanmcclean** [comment]
I meant - what sort of columns/informations do you need? 😅 

Are you putting it into some accounting software - do they have documentation of what stuff you need?

**Comment by remiduval** [comment]
I don't think they use an accounting software themselves, they'd use the export to:
- report to their accountant the amount of sales for each product during a specific range of dates
- communicate student info (that I store in product metadata fields) to an insurance company when parents buy an insurance for their kid

Ideally, there would be one line per product bought in the export (as their could be several products per order)

Columns I had in mind:
- Order number
- Date
- Customer name
- Email
- Address
- Postcode
- City
- Country
- Product ID (in case 2 products have the same name)
- Product name
- Variant
- Quantity
- Product total
- Metadata 1 (if it exists)
- Metadata 2 (etc)

I didn't include fields related to shipping as I don't use them but they could be useful for others

**Comment by duncanmcclean** [comment]
Cool, I'll see what I can do.

**Comment by duncanmcclean** [comment]
Just had some time to look into this.

I originally planned to add it as a feature inside Simple Commerce Core but people's needs for exports vary (which columns do they need, which filetype etc). It also fits into a nice feature I'm planning for v2.4 or v2.5 so it'll probably get added then.

With that in mind, I built out a basic sales exporter for you and popped it into a Gist for you to copy into your project: https://gist.github.com/duncanmcclean/f95905c1d129659d509a94ea242ad0f8

If you wanted to get fancy, you could put it in a [CP Utility](https://statamic.dev/extending/utilities#content) or something but that's up to you!

Closing for now but it's on my roadmap for the future!

**Comment by remiduval** [comment]
That's great, thank you!
I followed your advice and created a CP Utility - wasn't easy but it works now.

Can't wait to see the export feature when it's released.
Thanks again!

**Comment by duncanmcclean** [comment]
No worries! Have a great day 😄

**Comment by remiduval** [comment]
Hey Duncan! Sorry to bother with this but I'm having some issues with the exported file:
1/ I have one line per product for each order, but the variant, quantity & price are the same for all products (even though they aren't in the actual order)
2/ Some of the extra fields (metadata) are inserted in columns far away, leaving many blank columns before (my columns go all the way to BFW 😅)
3/ The prices are indicated raw (eg. 1600 instead of 16.00) - I'll look into the code as I might be able to solve this myself

Thank you!

**Comment by duncanmcclean** [comment]
Hey!

I don't have much time to have a proper look at debugging this for you but I have a couple of ideas/suspicions...

1. Maybe it's being overridden somewhere with the one from the last line item?
2. What are you wanting them to be instead of being blank? If you've got no data, there's nothing to put there 😅 
3. You can use a SC helper method to return with a decimal/float number instead...

```php
use DoubleThreeDigital\SimpleCommerce\Facades\Currency;

(float) Currency::toDecimal($order->get('total'))
```

**Comment by remiduval** [comment]
Thank you for the suggestions :) I just had the time to look at it:
1. I'm not sure, everything looks ok in the code you wrote and I don't understand why/if it gets overwritten by the last item
2. I'd like metadatas to start on column X, for all lines in the export. The issue seems to be
 - Product A has metadata "Apples" & metadata "Peaches" = metadatas displayed on column X and Y
 - Product B has metadata "Cats" & metadata "Dogs" = **metadatas displayed on column Z and AA, when I'd like them on column X and Y**
It's not problematic on a small amount of different metadatas but in my case, this brings me to have metadatas starting on column BFW for some lines (and client not seeing them)
3. Works like a charm, thanks!

I think I can't fix 1. and 2. with my knowledge but maybe it's best to wait for the Export feature you talked about? 💫

**Comment by duncanmcclean** [comment]
The new exports feature is months out - haven't started planning that release yet.

**Comment by remiduval** [comment]
Hello Duncan!

I've managed to fix issues 2. & 3. by myself but I'm still struggling with 1. (in the export, when there are several products in an order, the product lines get overwritten by the last product line of the order).
I think I've identified where the overwriting comes from but I struggle to find a fix: https://gist.github.com/duncanmcclean/f95905c1d129659d509a94ea242ad0f8#file-salesexport-php-L29

If you have any lead on this, it would be great 🙌🏼  - thank you!

**Comment by duncanmcclean** [comment]
Can't think off the top of my head why it might not be working but I'll certainly take a look when I have some spare time (probably at the weekend now). I hope that's okay?

**Comment by remiduval** [comment]
That would be of great help, thank you!

**Comment by duncanmcclean** [comment]
I've figured it out & updated the gist!

I changed two things:

1. After this line `return $lineItems->map(function ($lineItem) use ($order) {`, I added `$order = $order->fresh();`
2. Then instead of `$order->set($key, $value)`, I did `$order->data()->put($key, $value);`

Hopefully that fixes the issue for you!

**Comment by remiduval** [comment]
Thank you so much! It works properly now.

I also changed
https://gist.github.com/duncanmcclean/f95905c1d129659d509a94ea242ad0f8#file-salesexport-php-L59
for
`optional($order->augmentedValue('customer')->value())->email()`
to get the customer email in the output.

**Comment by duncanmcclean** [comment]
Awesome! Glad it's working 😄
